apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion setup.compileSdk
    namespace "pl.szczodrzynski.edziennik.wear.data"

    defaultConfig {
        minSdkVersion setup.minSdk
        targetSdkVersion setup.targetSdk
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    api 'com.google.code.gson:gson:2.11.0'
}
